language: node_js

node_js:

  - "node"

install:

  - mkdir uploads/images
  - mkdir uploads/videos

after_success: 
  
  - npm run coverage

env:
  - JWT_KEY: "secret"

cache:

  directories:

    - "node_modules"
    - "uploads"